# Generated by Django 5.2.7 on 2025-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('host', 'Host'), ('admin', 'Admin')], max_length=128),
        ),
    ]
